version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-with-vite
    privileged: true
    ports:
      - "51730:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - rede-1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: express-with-sequelize
    privileged: true
    volumes:
      - ./backend:/app
    depends_on:
      - database
    ports:
      - 30010:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001
    networks:
      - rede-1
      - rede-2

  database:
    image: mysql:8.0.29
    container_name: farmGroupDB
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: farmGroupDB
    ports:
      - 33060:3306
    volumes:
      - ./:/docker-entrypoint-initdb.dw
    networks:
      - rede-2

networks:
  rede-1:
  rede-2: